#!/bin/bash
# tmux-command-center: Start a three window session (system, tools, misc) using
# PWD as the name of the session.
# Copyright (C) 2015 Sam Morrison
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Current repository directory name.
PROJECT=${PWD##*/}

# Set PWD as default pauth for tmux session
tmux set-option default-path "$PWD"

# Create new session and define initial window
tmux new-session -d -s "$PROJECT" -n 'system'

# Create windows
tmux new-window -t "$PROJECT:2" -n 'tools'
tmux new-window -t "$PROJECT:3" -n 'misc'
tmux select-window -t "$PROJECT:1"

# Attach session
tmux -2 attach-session -t "$PROJECT"
